---
- name: Deploy RHV VM
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - name: Deploy Instances
      include_role:
        name: rhv
        tasks_from: main.yml
      vars:
        instances:
          name: weblxonp01
          template:
          






    - name: "Add {{ var_rhv_vmname }} to In-Memory Inventory"
      add_host:
        name: "{{ var_rhv_vmname }}"
        groups:
          - "{{ r_deploy_rhv.vm.comment }}"
          - just_created
